# Site settings
title: Tech Talks
email: madhukaraphatak@gmail.com
description: "Its a collection of technical talks that I enjoyed watching. I have avoided putting product announcements or company specific talks.You can also contribute to the list by forking on github."
baseurl: "/techtalks"
url: "http://phatak-dev.github.io"
username : phatak-dev
twitter : madhukaraphatak
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
